'use strict';
// No private records or pending mutation bodies are persisted in browser storage.
var appointmentPending=null;
(()=>{
 const journal=window.PracticeStaffActions('client');
 const $=id=>document.getElementById(id);let selected=null,epoch=0,role=null,pendingPath=null,supportClaim=null,supportData=null;
 const guidance={full_refund_review:'Our cancellation policy allows a full refund with at least 24 hours’ notice. Staff must review and process it separately.',staff_review:'Staff must review the appointment’s change history and notice period before deciding any refund. This action does not issue one.',late_reschedule_review:'With under 12 hours’ notice, our cancellation policy offers one complimentary reschedule within 14 days instead of a cash refund. Do not cancel as a substitute for arranging a reschedule.'};
 const messages={original_time_review_required:'The original appointment time needs a private review before a late move. Your appointment has not changed.',invalid_request:'Please check the details, then open the booking again before saving.',support_verification_unavailable:'We could not match the verified payment to this saved booking. No change has been made.',support_wait:'Three access codes have already been issued for this booking in the last hour. Please wait before issuing another.',booking_unavailable:'No saved booking matches that reference.',access_unavailable:'Your access could not be confirmed. Sign in again.',appointment_unavailable:'This appointment cannot be changed here. Refresh the calendar.',revision_changed:'This appointment has changed. Open its latest details before proceeding.',request_conflict:'This request differs from an earlier saved change. Keep it for support; do not create another change.',invalid_change:'Check the new time and reason.',time_unavailable:'Choose an available practice time with at least 30 minutes’ notice. Your original appointment has not moved.',time_already_reserved:'That time is already reserved. Your original appointment has not moved.',late_reschedule_used:'This booking has already used its one late reschedule. Contact the practice for help.',please_wait:'Please wait a moment before trying again.'};
 function sync(){calendarSyncBusy();$('appointment-repeat').disabled=busy;$('appointment-repeat').hidden=!appointmentPending||pendingPath==='support';$('support-repeat').hidden=!appointmentPending||pendingPath!=='support';$('support-repeat').disabled=busy;}
 function clear(){++epoch;selected=null;appointmentPending=journal.get()[0]||null;pendingPath=appointmentPending?'check':null;role=null;$('appointment-detail').hidden=true;$('appointment-summary').replaceChildren();$('appointment-policy').textContent='';$('appointment-status').textContent='';$('appointment-cancel').reset();$('appointment-reschedule').reset();supportClaim=null;supportData=null;$('booking-support-change').hidden=true;$('booking-support-change').reset();$('support-code-result').hidden=true;$('support-code').textContent='';$('booking-lookup').reset();$('booking-support').hidden=true;$('booking-support-content').replaceChildren();$('booking-support-status').textContent='';sync();}
 async function api(path,body){const response=await fetch('/api/studio/appointments/'+path,{method:'POST',credentials:'same-origin',cache:'no-store',redirect:'error',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});studioCheckAccess(response);if(!response.headers.get('content-type')?.includes('application/json'))throw Error('unavailable');const data=await response.json();if(!response.ok){const e=Error('unavailable');e.code=data.code;e.status=response.status;throw e;}return data;}
 function fail(e){if(e.status===403||e.status===401){clear();setBusy(false);$('status').textContent=messages.access_unavailable;$('retry').hidden=false;}else $('appointment-status').textContent=journal.error||messages[e.code]||'We could not confirm the result. Check the same change before making another change.';}
 document.addEventListener('studio-appointment',async event=>{
  if(role!=='client'||busy||calendarPending||appointmentPending)return;setBusy(true);const ticket=epoch;selected=null;$('appointment-detail').hidden=true;$('appointment-summary').replaceChildren();$('appointment-policy').textContent='';$('appointment-cancel').hidden=true;$('appointment-reschedule').hidden=true;
  try{const data=await api('detail',{claim_id:event.detail});if(ticket!==epoch)return;
   if(data.code!=='ok'||data.claim_id!==event.detail||!Number.isInteger(data.revision)||data.revision<1||typeof data.can_cancel!=='boolean'||!Object.hasOwn(guidance,data.policy_guidance)||!Number.isFinite(Date.parse(data.starts_at)))throw Error('unavailable');
   selected=data;$('appointment-summary').replaceChildren();for(const text of [data.name,data.service,calendarTime.format(new Date(data.starts_at))+' · '+calendarZone,'Status: '+data.state,'Reference: '+data.reference]){const p=document.createElement('p');p.textContent=text;$('appointment-summary').append(p);}
   $('appointment-policy').textContent=guidance[data.policy_guidance];$('appointment-cancel').reset();$('appointment-cancel').hidden=!data.can_cancel;$('appointment-reschedule').hidden=!data.can_reschedule;$('appointment-reschedule').reset();$('appointment-status').textContent='';$('appointment-detail').hidden=false;$('appointment-title').focus();
  }catch(e){if(ticket===epoch){$('appointment-detail').hidden=false;fail(e);}}
  finally{if(ticket===epoch){setBusy(false);sync();}}
 });
 async function save(){if(role!=='client'||busy||!appointmentPending)return;if(pendingPath==='check'){await checkSaved();return;}setBusy(true);const ticket=epoch;const support=pendingPath==='support';$(support?'booking-support-status':'appointment-status').textContent='Saving your verified change…';
  try{await journal.remember(appointmentPending.operation_id);if(ticket!==epoch)return;const result=await api(pendingPath,appointmentPending);if(ticket!==epoch)return;
   if(support){const corrected=appointmentPending.action==='contact_correction';if(result.code!=='support_saved'||result.revision!==appointmentPending.expected_revision+(corrected?1:0)||typeof result.active!=='boolean'||!Number.isFinite(Date.parse(result.expires_at))||(result.active&&!/^[0-9]{8}$/.test(result.activation_code)))throw Error('unavailable');
    await journal.forget(appointmentPending.operation_id);if(ticket!==epoch)return;appointmentPending=null;pendingPath=null;supportData=null;$('booking-support-change').hidden=true;$('support-code-result').hidden=!result.active;$('support-code').textContent=result.active?result.activation_code:'';$('support-code-note').textContent='Access code · expires '+calendarTime.format(new Date(result.expires_at))+' '+calendarZone;
    $('booking-support-status').textContent=result.active?(corrected?'Contact details corrected. Old receipt access is revoked. Updated meeting and record copies are queued. Give the customer this access code during the verified call.':'Access code prepared. Give it only to the customer during the verified call.'): 'The earlier support action was saved, but its code is no longer active. Look up the booking again if more help is needed.';
    if(corrected){$('booking-support-content').replaceChildren();$('booking-support-manage').hidden=true;$('appointment-detail').hidden=true;selected=null;}return;
   }
if(result.code!==(pendingPath==='cancel'?'cancelled':'rescheduled')||result.revision!==appointmentPending.expected_revision+1)throw Error('unavailable');const moved=pendingPath==='reschedule';if(moved&&!Number.isFinite(Date.parse(result.starts_at)))throw Error('unavailable');await journal.forget(appointmentPending.operation_id);if(ticket!==epoch)return;appointmentPending=null;pendingPath=null;selected=null;
   for(const line of $('appointment-summary').children){if(line.textContent.startsWith('Status:'))line.textContent=moved?'Status: confirmed':'Status: cancelled';if(moved&&line.textContent.endsWith(' · '+calendarZone))line.textContent=calendarTime.format(new Date(result.starts_at))+' · '+calendarZone;}
   $('appointment-cancel').hidden=true;$('appointment-reschedule').hidden=true;if(moved)$('appointment-policy').textContent=guidance.staff_review;$('appointment-status').textContent=moved?'Appointment moved. The original time is available again. Updated meeting details and record copies are queued. No extra payment is requested.':'Appointment cancelled. Its time is available again. Meeting, email and record updates are queued. No refund has been issued by this action.';setBusy(false);await calendarLoad();}
  catch(e){if(ticket!==epoch)return;if(e.status===422||['appointment_unavailable','revision_changed','invalid_change','time_unavailable','time_already_reserved','late_reschedule_used','original_time_review_required','booking_unavailable','support_verification_unavailable','support_wait'].includes(e.code)){try{await journal.forget(appointmentPending.operation_id);}catch{fail(e);return;}if(ticket!==epoch)return;appointmentPending=null;pendingPath=null;selected=null;$('appointment-cancel').hidden=true;$('appointment-reschedule').hidden=true;if(support){supportData=null;$('booking-support-change').hidden=true;}}if(support&&e.status!==403&&e.status!==401)$('booking-support-status').textContent=journal.error||journal.error||messages[e.code]||'We could not confirm the result. Check the same support action before doing anything else.';else fail(e);}
  finally{if(ticket===epoch){setBusy(false);sync();}}
 }
 async function checkSaved(){
  if(role!=='client'||busy)return;setBusy(true);const ticket=epoch;
  try{const saved=journal.get();if(journal.error)throw Error(journal.error);for(const item of saved){const result=await api('action-result',{operation_id:item.operation_id});if(ticket!==epoch)return;
   if(result.operation_id!==item.operation_id||result.code==='operation_conflict')throw Error('unavailable');
   if(result.code==='operation_not_found'){if(Date.now()-item.created_at<300000)throw Error('still_checking');await journal.forget(item.operation_id);if(ticket!==epoch)return;continue;}
   if(!['cancelled','rescheduled','support_saved','refund_verified','resource_reviewed'].includes(result.code))throw Error('unavailable');
   await journal.forget(item.operation_id);if(ticket!==epoch)return;
   if(result.active&&/^[0-9]{8}$/.test(result.activation_code)){$('support-code-result').hidden=false;$('support-code').textContent=result.activation_code;$('support-code-note').textContent='Give this code only to the verified customer. It expires fifteen minutes after creation.';}
  }appointmentPending=journal.get()[0]||null;pendingPath=appointmentPending?'check':null;selected=null;supportData=null;supportClaim=null;
   $('appointment-cancel').hidden=true;$('appointment-reschedule').hidden=true;$('booking-support-change').hidden=true;
   $('appointment-detail').hidden=false;$('appointment-status').textContent='Earlier actions checked. Find the booking again before another change.';
  }catch(error){if(ticket===epoch)fail(error);}
  finally{if(ticket===epoch){setBusy(false);sync();}}
 }
 $('appointment-cancel').addEventListener('submit',e=>{e.preventDefault();if(role!=='client'||busy||calendarPending||appointmentPending||!selected||!$('appointment-ack').checked)return;pendingPath='cancel';appointmentPending={operation_id:crypto.randomUUID(),claim_id:selected.claim_id,expected_revision:selected.revision,reason:$('appointment-reason').value.trim()};save();});
 $('appointment-reschedule').addEventListener('submit',async e=>{
  e.preventDefault();if(role!=='client'||busy||calendarPending||appointmentPending||!selected)return;
  const start=$('appointment-start').value,ticket=epoch,target=selected;if(!start)return;setBusy(true);
  try{
   const starts_at=await calendarResolve(start);if(ticket!==epoch)return;
   pendingPath='reschedule';appointmentPending={operation_id:crypto.randomUUID(),claim_id:target.claim_id,expected_revision:target.revision,reason:$('appointment-move-reason').value.trim(),starts_at};
   setBusy(false);await save();
  }catch(error){if(ticket===epoch)$('appointment-status').textContent=calendarMessages[error.code]||'We could not check that time. Refresh the calendar and try again.';}
  finally{if(ticket===epoch)setBusy(false);}
 });
 $('booking-lookup').addEventListener('submit',async e=>{
  e.preventDefault();if(role!=='client'||busy||calendarPending||appointmentPending)return;const reference=$('booking-reference').value.trim();
  if(!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(reference)){$('booking-support-status').textContent='Enter the complete booking reference.';return;}
  setBusy(true);const ticket=epoch;supportClaim=null;supportData=null;$('booking-support-change').hidden=true;$('support-code-result').hidden=true;$('support-code').textContent='';$('booking-support').hidden=true;$('booking-support-content').replaceChildren();$('booking-support-status').textContent='Checking the saved booking…';
  try{const data=await api('lookup',{reference});if(ticket!==epoch)return;
   if(data.code!=='ok'||data.reference!==reference.toLowerCase()||!Array.isArray(data.payments)||data.payments.length>20)throw Error('unavailable');
   const add=text=>{const p=document.createElement('p');p.textContent=text;$('booking-support-content').append(p);};
   for(const text of [data.name,data.service,'Status: '+data.state,'Email: '+(data.email||'Not provided'),'Phone: '+data.phone,'Time: '+calendarTime.format(new Date(data.starts_at))+' · '+calendarZone,'Unresolved payment checks: '+data.unresolved_payments])add(text);
   add('Payment observations below are saved evidence, not permission to issue a refund. Repeated observations of the same payment must not be added together.');
   for(const entry of data.payments)add((entry.observed_at&&Number.isFinite(Date.parse(entry.observed_at))?calendarTime.format(new Date(entry.observed_at))+' · '+calendarZone+' · ':'')+entry.payment_id+' · '+entry.status+' · amount INR '+(entry.amount_paise/100).toFixed(2)+' · refunded INR '+(entry.refunded_paise/100).toFixed(2));
   if(!data.payments.length)add('No payment evidence has been recorded yet.');supportData=data;$('booking-support-change').reset();$('support-contacts').hidden=true;$('support-email').required=false;$('support-phone').required=false;$('support-email').value=data.email||'';$('support-phone').value=data.phone;$('booking-support-change').hidden=data.state==='held';supportClaim=data.claim_id;$('booking-support-manage').hidden=!supportClaim;$('booking-support').hidden=false;$('booking-support-status').textContent='Saved booking found. A missing customer receipt does not mean the booking is lost.';
  }catch(error){if(ticket!==epoch)return;if(error.status===403||error.status===401)fail(error);else $('booking-support-status').textContent=messages[error.code]||'We could not load this booking. Please try again.';}
  finally{if(ticket===epoch){setBusy(false);sync();}}
 });
 $('booking-support-manage').addEventListener('click',()=>{if(supportClaim&&!busy&&!appointmentPending)document.dispatchEvent(new CustomEvent('studio-appointment',{detail:supportClaim}));});
 document.addEventListener('studio-booking-reference',event=>{if(role!=='client'||busy||calendarPending||appointmentPending)return;$('booking-reference').value=event.detail;$('booking-lookup').requestSubmit();$('booking-lookup').scrollIntoView({block:'start'});});
 $('support-action').addEventListener('change',()=>{const corrected=$('support-action').value==='contact_correction';$('support-contacts').hidden=!corrected;$('support-email').required=corrected && supportData?.contact_email_required!==false;$('support-phone').required=corrected;});
 $('booking-support-change').addEventListener('submit',e=>{e.preventDefault();if(role!=='client'||busy||calendarPending||appointmentPending||!supportData||!$('support-verified').checked)return;
  const action=$('support-action').value;pendingPath='support';appointmentPending={operation_id:crypto.randomUUID(),reference:supportData.reference,expected_revision:supportData.revision,action,reason:$('support-reason').value.trim(),verified_payment_id:$('support-payment').value.trim(),verification_confirmed:true,...(action==='contact_correction'?{email:$('support-email').value.trim()||null,phone:$('support-phone').value.trim()}:{})};save();});
 $('support-repeat').textContent='Check saved action';$('support-repeat').addEventListener('click',checkSaved);
 $('appointment-repeat').textContent='Check saved action';$('appointment-repeat').addEventListener('click',checkSaved);
 document.addEventListener('studio-busy',sync);
 document.addEventListener('studio-calendar-hide',clear);
 document.addEventListener('studio-role',event=>{clear();role=event.detail;if(role==='client'&&appointmentPending){$('appointment-detail').hidden=false;$('appointment-status').textContent='An earlier action needs checking before another change.';}sync();});
})();
