DO $test$
DECLARE c uuid:=gen_random_uuid(); r uuid:=gen_random_uuid(); r2 uuid:=gen_random_uuid();
 p jsonb; v text; result jsonb; expected jsonb; day date:=(clock_timestamp() AT TIME ZONE 'Asia/Kolkata')::date+1;
BEGIN
 ASSERT NOT EXISTS(SELECT 1 FROM sarsa_booking.bookings),'Use empty development branch only';
 IF extract(isodow FROM day)=7 THEN day:=day+1; END IF;
 SELECT policy_version INTO v FROM sarsa_booking.intake_settings;
 INSERT INTO sarsa_booking.checkout_contexts(id,credential_digest,expires_at) VALUES(c,repeat('4',64),clock_timestamp()+interval '24 hours');
 p:=jsonb_build_object('service_id','kundli-prediction','quote_version',v,'starts_at',to_char((day::text||' 10:00 Asia/Kolkata')::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS"Z"'),'full_name','Synthetic Only','email','test@example.invalid','phone','+919876543210');
 GRANT sarsa_booking_web TO neondb_owner;
 SET LOCAL ROLE sarsa_booking_web;
 ASSERT NOT has_function_privilege(current_user,'sarsa_booking.reserve_checkout(uuid,uuid,text,text,jsonb)','EXECUTE');
 ASSERT sarsa_booking.admit_checkout(c,r,repeat('a',64),repeat('b',64))='pending';
 result:=sarsa_booking.reserve_configured_checkout(c,r,repeat('a',64),repeat('b',64),p,NULL);
 ASSERT result->>'code'='payment_not_configured',result::text;
 ASSERT NOT EXISTS(SELECT 1 FROM sarsa_booking.bookings);
 RESET ROLE;
 UPDATE sarsa_booking.intake_settings SET public_open=true,merchant_id='syntheticOnly',payment_mode='live',credential_version='syntheticOnly';
 expected:=jsonb_build_object('merchant_id','syntheticOnly','mode','live','credential_version','syntheticOnly');
 SET LOCAL ROLE sarsa_booking_web;
 result:=sarsa_booking.reserve_configured_checkout(c,r,repeat('a',64),repeat('b',64),p,expected);
 ASSERT result->>'code'='request_rejected',result::text;
 ASSERT sarsa_booking.admit_checkout(c,r2,repeat('c',64),repeat('d',64))='pending';
 result:=sarsa_booking.reserve_configured_checkout(c,r2,repeat('c',64),repeat('d',64),p,expected);
 ASSERT result->>'code'='reserved',result::text;
 result:=sarsa_booking.reserve_configured_checkout(c,r2,repeat('c',64),repeat('d',64),p,NULL);
 ASSERT result->>'code'='existing',result::text;
 result:=sarsa_booking.reserve_configured_checkout(c,r2,repeat('x',64),repeat('d',64),p,NULL);
 ASSERT result->>'code'='request_conflict',result::text;
 RESET ROLE;
END $test$;
