/** Focused Version A restoration: actual compiled app, synthetic requests only. */
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {chromium} from 'playwright-core';
import {startReview} from './review-server.mjs';
import {fixture,ready,paths,viewports} from './browser-fixtures.mjs';
const output=resolve(process.env.SARSA_EVIDENCE_DIR||'/tmp/sarsa-version-a-browser');mkdirSync(output,{recursive:true});
const report={kind:'version-A-restoration-focused-synthetic',started:new Date().toISOString(),routes:[],layouts:[],bookings:[],enquiries:[],motion:[],failures:[]};
const server=await startReview(),origin=server.origin,browser=await chromium.launch({headless:true});
async function run(label,fn,options={}){const context=await browser.newContext(options),f=await fixture(context,origin,options),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));try{await fn(page,f,context);assert.deepEqual(errors,[]);assert.deepEqual(f.blocked,[]);}catch(error){report.failures.push({label,error:error.stack});await page.screenshot({path:resolve(output,'failed-'+label.replaceAll('/','-')+'.jpg'),fullPage:true});}finally{await context.close();}}
try{
 for(const width of [390,1440])for(const path of paths)await run('route-'+width+path,async(page)=>{await ready(page,path,origin);await page.waitForTimeout(100);assert.equal(await page.locator('#page-content h1').count(),1);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth);assert(overflow<=1,'overflow '+overflow);assert.equal(await page.locator('[data-motion]').count(),0);assert.equal(await page.locator('.sarsa-motion-scene').count(),0);await page.screenshot({path:resolve(output,'route-'+width+(path==='/'?'-home':path.replaceAll('/','-'))+'.jpg'),fullPage:true});report.routes.push({path,width,overflow,status:'passed'});},{viewport:{width,height:width===390?844:900},reducedMotion:'reduce'});
 for(const [width,height] of viewports)await run('layout-'+width,async(page)=>{await ready(page,'/booking',origin);const layout=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth-innerWidth,services:document.querySelectorAll('input[name=service]').length,steps:document.querySelectorAll('.journey-nav button').length,sections:['service','appointment','details','review'].every(id=>document.getElementById(id)),headers:document.querySelectorAll('.site-header').length}));assert(layout.overflow<=1);assert.equal(layout.services,4);assert.equal(layout.steps,4);assert(layout.sections);assert.equal(layout.headers,1);report.layouts.push({width,height,...layout,status:'passed'});},{viewport:{width,height},reducedMotion:'reduce'});
 for(const otp of [false,true])for(const width of [390,1440])await run('booking-'+width+'-'+otp,async(page,f,context)=>{
  await ready(page,'/booking',origin);assert.equal(await page.locator('#email').getAttribute('required')!==null,otp);
  await page.locator('.service-card').filter({hasText:'Kundli Matching'}).click();await page.waitForTimeout(300);
  await page.locator('.abs-date-group').first().click();assert.equal(await page.getByRole('dialog',{name:'Appointment date'}).count(),1);
  const label=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(Date.now()+86400000));await page.getByRole('button',{name:new RegExp(label)}).click();await page.locator('.slot-option').first().click();await page.getByRole('button',{name:'Fill your details →',exact:true}).click();
  await page.locator('#full_name').fill('Synthetic Restoration Visitor');await page.locator('#phone').fill('9876543210');await page.locator('#notes').fill('Local restoration check only.');
  if(otp){await page.locator('#email').fill('review@example.invalid');await page.getByRole('button',{name:'Send email code',exact:true}).click();await page.getByLabel('Email verification code',{exact:true}).fill('123456');}
  await page.evaluate(()=>{globalThis.retainedBookingNodes={form:document.querySelector('.sarsa-booking form'),name:document.querySelector('#full_name'),date:document.querySelector('.abs-date-group'),phone:document.querySelector('#phone')};});
  const before={name:await page.locator('#full_name').inputValue(),slot:await page.locator('input[name=time]:checked').inputValue()};
  await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:768,height:1024});const other=await context.newPage();await other.goto('about:blank');await page.bringToFront();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.waitForTimeout(400);
  assert.equal(await page.locator('#full_name').inputValue(),before.name);assert.equal(await page.locator('input[name=time]:checked').inputValue(),before.slot);assert(await page.evaluate(()=>Object.entries(retainedBookingNodes).every(([key,node])=>node===document.querySelector({form:'.sarsa-booking form',name:'#full_name',date:'.abs-date-group',phone:'#phone'}[key]))));
  if(otp){assert.equal(await page.getByLabel('Email verification code',{exact:true}).inputValue(),'123456');assert.equal(f.calls.filter(c=>c.path==='/api/booking-verification/start').length,1);await page.getByRole('button',{name:'Verify code',exact:true}).click();await page.getByText('Your email address is verified.',{exact:true}).waitFor();}
  await other.close();await page.setViewportSize({width,height:width===390?844:900});await page.getByRole('button',{name:'Review your booking →',exact:true}).click();await page.getByRole('checkbox',{name:/I’ve checked/}).check();await page.getByRole('button',{name:/Continue to payment ·/}).click();await page.getByRole('heading',{name:'Your appointment is confirmed',exact:true}).waitFor();await page.getByRole('button',{name:'Check booking status',exact:true}).click();await page.waitForTimeout(200);assert.equal(await page.locator('[role=alert]').count(),0);
  await page.getByRole('button',{name:'Email appointment details',exact:true}).click();if(!otp){await page.getByLabel('Email address for this copy',{exact:true}).fill('review@example.invalid');await page.getByRole('button',{name:'Send email copy',exact:true}).click();}await page.getByText('Your email-copy request is saved. Delivery status is shown below.',{exact:true}).waitFor();assert.equal(f.calls.filter(c=>c.path==='/api/checkout').length,1);await page.screenshot({path:resolve(output,`confirmed-${width}-otp-${otp}.jpg`),fullPage:true});report.bookings.push({width,otp,retainedNodes:4,checkouts:1,emailCopies:f.calls.filter(c=>c.path==='/api/checkout/email-details').length,status:'passed'});
 },{viewport:{width,height:width===390?844:900},otp});
 for(const width of [390,1440])await run('contact-'+width,async(page,f,context)=>{await ready(page,'/contact',origin);await page.locator('#visitor-name').fill('Synthetic Restoration Visitor');await page.locator('#visitor-email').fill('review@example.invalid');await page.locator('#message').fill('Synthetic restoration only. No real enquiry is sent.');const name=await page.locator('#visitor-name').elementHandle();const other=await context.newPage();await other.goto('about:blank');await page.bringToFront();assert.equal(await page.locator('#visitor-name').inputValue(),'Synthetic Restoration Visitor');assert(await page.locator('#visitor-name').evaluate((node,old)=>node===old,name));await other.close();await page.getByRole('button',{name:/Continue to email verification/}).click();await page.locator('#code').fill('000000');await page.getByRole('button',{name:/Verify.*send enquiry/}).click();await page.locator('#form-status').filter({hasText:/code|verification/i}).waitFor();await page.locator('#code').fill('123456');await page.getByRole('button',{name:/Verify.*send enquiry/}).click();await page.locator('#outcome').waitFor();assert.equal(await page.evaluate(()=>document.activeElement.id),'outcome');assert.equal(f.calls.filter(c=>c.path==='/api/contact/start').length,1);await page.getByRole('button',{name:'Write another enquiry',exact:true}).click();await page.locator('#visitor-name').waitFor();assert.equal(await page.locator('#visitor-name').inputValue(),'');report.enquiries.push({width,retainedDraft:true,wrongCodeRejected:true,received:true,restartCleared:true,status:'passed'});},{viewport:{width,height:width===390?844:900},reducedMotion:'reduce'});
 await run('motion',async(page)=>{await ready(page,'/',origin);await page.waitForTimeout(4500);const hero=await page.locator('#welcome').getAttribute('data-motion-progress');assert.equal(hero,'1.000');for(const id of ['madhuri','conversation','process','questions']){await page.locator('#'+id).scrollIntoViewIfNeeded();await page.waitForTimeout(3100);const p=await page.locator('#'+id).getAttribute('data-motion-progress');assert.equal(p,'1.000');report.motion.push({page:'/',section:id,progress:p,status:'passed'});}await page.screenshot({path:resolve(output,'home-motion-settled.jpg'),fullPage:true});},{viewport:{width:1440,height:900},reducedMotion:'no-preference'});
 for(const mode of ['off','unknown'])await run('mode-'+mode,async(page,f)=>{await ready(page,'/contact',origin);assert.equal(await page.locator('#visitor-name').count(),1);await ready(page,'/booking',origin);assert.equal(await page.locator('input[name=service]').count(),0);assert.equal(f.calls.filter(c=>c.path==='/api/checkout').length,0);report.layouts.push({mode,status:'passed'});},{viewport:{width:390,height:844},mode,reducedMotion:'reduce'});
}finally{await browser.close();await server.close();report.finished=new Date().toISOString();writeFileSync(resolve(output,'report.json'),JSON.stringify(report,null,2)+'\n');}
console.log(JSON.stringify({routes:report.routes.length,layouts:report.layouts.length,bookings:report.bookings.length,enquiries:report.enquiries.length,motion:report.motion.length,failures:report.failures,output}));if(report.failures.length)process.exitCode=1;
