import React, { useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { useBooking } from '../booking/useBooking.jsx';
import { money, appointmentLabel, timeLabel, indiaDate, dateRange } from '../booking/protocol.mjs';
import { mountBookingMotion } from '../booking/motion.mjs';
import '../booking/booking.css';
import {createVerificationFields} from '../../../appointment-system/browser/booking/verification-fields.mjs';
const VerificationFields=createVerificationFields(React);

const descriptions = {
  'kundli-prediction':['Kundli Prediction','A birth-chart perspective on your questions and life’s transitions.'],
  'kundli-matching':['Kundli Matching','Relationship questions through the lens of birth-chart compatibility.'],
  'vastu-consultation':['Vastu Consultation','A considered look at your home or workspace through Vastu.'],
  numerology:['Numerology','Explore the patterns associated with names, dates and numbers.'],
};
function Symbol({id}) {
  if(id==='numerology')return <span className="number-symbol" aria-hidden="true">3<em>6</em>9</span>;
  return <svg viewBox="0 0 80 80" aria-hidden="true">{id==='kundli-matching'
    ? <><circle cx="29" cy="40" r="23"/><circle cx="51" cy="40" r="23"/><path d="M40 14v52"/></>
    : id==='vastu-consultation' ? <><rect x="14" y="14" width="52" height="52"/><path d="M40 5v70 M5 40h70 M14 14 66 66 M66 14 14 66"/></>
    : <><path d="M40 5 75 40 40 75 5 40Z M5 40H75 M40 5V75 M22 22 58 58 M58 22 22 58"/><circle cx="40" cy="40" r="16"/></>}</svg>;
}
function go(id) {
  const section=document.getElementById(id); if(!section)return;
  section.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});
  section.querySelector('h2')?.focus({preventScroll:true});
}
function Go({id,children,className='text-button'}) {return <button type="button" className={className} onClick={()=>go(id)}>{children}</button>}
function Receipt({state,check,resume,restart,canRetryOriginal,retryOriginal}) {
  const [clock,setClock]=useState(Date.now());
  useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer)},[]);
  const r=state.receipt;
  const offset=useMemo(()=>r?Date.parse(r.server_now)-Date.now():0,[r]);
  const cooling=clock<state.retryAt, disabled=state.busy||state.phase==='payment'||cooling;
  const titles={held:'Your time is reserved.',expired:'Let’s check the payment.',confirmed:'Your appointment is confirmed.',cancelled:'Your appointment is cancelled.',payment_review:'Your payment needs a closer look.'};
  const copy={held:'Your appointment will be confirmed after payment is checked. Closing the payment window does not cancel a payment.',
    expired:'The reserved time has expired. We still need to resolve the payment before you choose another time. Please do not pay again elsewhere.',
    confirmed:'Your consultation with Madhuri Gupta is booked. Meeting and email updates are shown below.',
    cancelled:'Please contact the practice if you need help with this appointment or its payment.',
    payment_review:'We need to check this payment before confirming the next step. Please contact the practice and do not pay again.'};
  const seconds=r?Math.max(0,Math.ceil((Date.parse(r.hold_expires_at)-clock-offset)/1000)):0;
  const email={not_queued:'Not yet queued',pending:'Preparing',processing:'Preparing',provider_accepted:'Accepted for sending',delivered:'Delivered',failed:'Delivery needs attention',attention:'Delivery needs attention',needs_attention:'Delivery needs attention',bounced:'Could not be delivered',complained:'Delivery needs attention'};
  return <section id="receipt" className={`appointment-receipt ${r?.appointment_state==='confirmed'?'confirmed':''}`} tabIndex="-1" aria-labelledby="receipt-title">
    <p className="eyebrow">YOUR APPOINTMENT</p><div className="receipt-heading"><h3 id="receipt-title">{r?titles[r.appointment_state]:'Checking your booking.'}</h3>{r?.appointment_state==='confirmed'&&<span id="receipt-seal" aria-hidden="true">✓</span>}</div>
    <p role="status">{r?copy[r.appointment_state]:'Your original booking request is saved in this browser. Please check its status before trying another payment.'}</p>
    {state.phase==='payment'&&<p role="status">The secure payment window is open. Finish or close that window to continue here.</p>}
    {r?.payment_state==='needs_attention'&&<p role="status">Your payment needs review. Please contact the practice before making another payment.</p>}
    {r?.appointment_state==='held'&&seconds>0&&<p id="hold-clock">Reserved time remaining: {Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</p>}
    {r&&<dl id="receipt-facts"><div><dt>Consultation</dt><dd>{r.service_name}</dd></div><div><dt>Appointment · {r.timezone}</dt><dd>{appointmentLabel(r.starts_at,r.timezone)}</dd></div><div><dt>Consultation fee</dt><dd>{money(r.amount_paise)}</dd></div><div><dt>Payment recorded</dt><dd>{r.captured_paise?money(r.captured_paise):'No captured payment recorded yet'}{r.refunded_paise>0&&<> · Refunded {money(r.refunded_paise)}</>}</dd></div><div><dt>Meeting</dt><dd>{r.meet_url?<a href={r.meet_url} target="_blank" rel="noopener noreferrer">Open your meeting ↗</a>:r.meeting_state==='needs_attention'?'Please contact the practice for your meeting link.':r.appointment_state==='confirmed'?'Your meeting link is being prepared.':'Available after confirmation'}</dd></div><div><dt>Confirmation email</dt><dd>{email[r.acknowledgement_state]||'Status being checked'}</dd></div><div><dt>Meeting-details email</dt><dd>{email[r.meeting_email_state]||'Status being checked'}</dd></div></dl>}
    <div className="receipt-reference"><span>Booking reference <strong>{state.credential.request_id}</strong></span></div>
    <div className="result-actions"><button type="button" className="button" disabled={disabled} onClick={check}>{state.busy?'Checking…':'Check booking status'}</button>
      {r?.next_actions.some(a=>['check_payment','resume_payment'].includes(a))&&<button type="button" className="button" disabled={disabled||seconds===0} onClick={resume}>Continue to payment ↗</button>}
      {r?.next_actions.includes('choose_new_time')&&<button type="button" className="button" disabled={disabled} onClick={restart}>Choose a new time</button>}
      {canRetryOriginal&&<button type="button" className="text-button" disabled={disabled} onClick={retryOriginal}>Retry the same saved request</button>}
      <Link className="text-button" to="/contact">Ask for help ↗</Link><a className="text-button" href="/booking-help">Restore lost booking access ↗</a></div>
    {cooling&&<p className="field-hint">Please wait {Math.ceil((state.retryAt-clock)/1000)} seconds before checking again.</p>}
    <p className="field-hint">Keep this tab available while your booking is being checked. Your private receipt stays in this browser tab and is never placed in a link.</p>
  </section>;
}
export default function Booking() {
  const [params]=useSearchParams();
  const flow=useBooking(params.get('service')||'kundli-prediction');
  const {state,dispatch}=flow, root=useRef(null), form=useRef(null);
  const locked=!!state.credential||state.phase==='blocked'||state.busy;
  const configured=state.policy?.policy.services.find(s=>s.id===state.service);
  const service=configured?{...configured,amount_paise:state.quote?.amount_paise??configured.pricing.amount_paise*state.questions}:null;
  const selectedName=service?.name||descriptions[state.service]?.[0]||'Choose a consultation';
  const timezone=state.policy?.policy.timezone||'Asia/Kolkata';
  const online=state.policy?.policy.meeting==='google_meet';
  const range=state.policy?dateRange(state.policy):null;
  const appointment=state.slot?appointmentLabel(state.slot.starts_at,timezone):'Still to choose';
  const maxDate=range?.last_date;
  useEffect(()=>{document.title='Book a consultation | Sarsa Jyotish Sansthan';window.scrollTo(0,0)},[]);
  useLayoutEffect(()=>mountBookingMotion(root.current),[]);
  const lastReceipt=useRef(false);
  useEffect(()=>{if(state.credential&&!lastReceipt.current){lastReceipt.current=true;document.getElementById('receipt')?.scrollIntoView({block:'center',behavior:'smooth'})}if(!state.credential)lastReceipt.current=false},[state.credential]);
  function detailsNext(){if(form.current.reportValidity())go('review')}
  function submit(event){event.preventDefault();if(!state.slot){dispatch({type:'error',message:'Please choose an available time first.'});go('appointment');return}flow.start()}
  return <div className="sarsa-booking" ref={root}>
    <header className="site-header wrap"><Link className="brand" to="/"><span className="brand-icon" aria-hidden="true">✳</span><span>Sarsa Jyotish Sansthan<small>WITH MADHURI GUPTA</small></span></Link><nav aria-label="Website"><Link to="/about">About Madhuri</Link><Link className="text-button" to="/contact">Ask before booking ↗</Link></nav></header>
    <section className="hero story-section wrap" id="welcome"><div className="hero-copy"><p className="eyebrow">A PERSONAL CONSULTATION</p><h1>A little space.<br/><em>Just for you.</em></h1><p className="lead">For the questions you carry.<br/>For a conversation with perspective.</p><p className="hero-body">Choose your consultation with Madhuri Gupta, find an available time, and book your appointment.</p><div className="actions"><Go id={state.credential?'review':'service'} className="button seal-button">{state.credential?'Check your booking':'Choose a consultation'} <i aria-hidden="true">↗</i></Go><Link className="text-button" to="/contact">Ask a question first</Link></div><div className="hero-foot"><span className="fine-line"/><p>One considered step at a time.</p></div></div><div className="folio-scene" aria-hidden="true"><div className="light-pool"/><div className="folio-shadow"/><div className="folio-paper"><span className="art-label">YOUR CONSULTATION</span><h2>Make room<br/>for what matters.</h2><div className="folio-rule"/><div className="folio-row"><span>01</span>A question worth exploring.</div><div className="folio-row"><span>02</span>A personal perspective.</div><div className="folio-stamp">S<span>J S</span></div><small>A THOUGHTFUL BEGINNING</small></div><div className="folio-cover cover-left"><span>S</span></div><div className="folio-cover cover-right"><span>J S</span></div><div className="invitation-tab"><small>THE NEXT CHAPTER</small><h3>Your time.<br/>Your conversation.</h3><span>↗</span></div></div></section>
    <nav className="journey-nav wrap" aria-label="Booking steps">{[['service','Consultation'],['appointment','Date & time'],['details','Your details'],['review','Review & pay']].map(([id,label],i)=><a key={id} href="#/booking" onClick={e=>{e.preventDefault();go(id)}}><span>0{i+1}</span>{label}</a>)}</nav>
    {state.error&&<div className="booking-alert wrap" role="alert"><p>{state.error}</p>{!state.policy&&!state.credential&&<button className="text-button" onClick={flow.loadPolicy} disabled={state.busy}>Reload consultation details</button>}<Link className="text-button" to="/contact">Contact the practice ↗</Link></div>}
    <form ref={form} onSubmit={submit}><fieldset className="draft-fields" disabled={locked}><legend className="sr-only">Appointment choices</legend>
      <section className="selection story-section wrap section-space" id="service" aria-labelledby="service-title"><div className="section-intro"><p className="eyebrow">01 / THE CONVERSATION</p><h2 id="service-title" tabIndex="-1">What brings<br/><em>you here?</em></h2><p>Start with the area that speaks to your questions. You can change your choice before you finish.</p><p className="section-note"><span>✦</span>A personal reading begins with a place to start.</p></div><div className="service-content"><div className="shelf-rail" aria-hidden="true"/><fieldset className="service-grid"><legend className="sr-only">Choose a consultation</legend>{(state.policy?.policy.services||[]).filter(s=>s.enabled).map((quote,i)=>{const id=quote.id;return <label className="service-card" key={id}><input type="radio" name="service" value={id} checked={state.service===id} disabled={!quote||locked} onChange={()=>dispatch({type:'edit',name:'service',value:id})}/><span className="service-top"><span className="card-number">0{i+1}</span><Symbol id={id}/></span><strong>{quote.name}</strong><span className="card-description">{descriptions[id]?.[1]||''}</span><span className="sample-fee">{quote?`${money(quote.pricing.amount_paise)} · ${quote.duration_minutes} minutes`:state.loadingPolicy?'Loading consultation details…':'Consultation details unavailable'}</span><span className="card-choice"><span>{state.service===id?'Selected consultation':'Choose consultation'}</span><span className="check" aria-hidden="true">✓</span></span></label>})}</fieldset><div className="section-action"><span className="selection-status">{selectedName}</span><Go id="appointment" className="button">Choose a time →</Go></div></div></section>
      <section className="appointment story-section section-space" id="appointment" aria-labelledby="appointment-title"><div className="wrap appointment-grid"><div className="section-intro"><p className="eyebrow">02 / A LITTLE TIME</p><h2 id="appointment-title" tabIndex="-1">Find a moment.<br/><em>Make some space.</em></h2><p>Choose a day, then a time that feels right. Your appointment is confirmed after payment is checked.</p><div className="appointment-mark" aria-hidden="true"><i/><span>✦</span></div><p className="request-note">Appointment times are shown in<br/>{timezone}</p></div><div className="appointment-window"><div className="window-frame" aria-hidden="true"/><div className="window-shutter" aria-hidden="true"/><div className="window-title"><span>YOUR APPOINTMENT</span><span aria-hidden="true">↗</span></div><p className="appointment-service">{selectedName}</p>{configured?.pricing.kind==='per_question'&&<div className="field"><label htmlFor="question-count">Number of questions</label><input id="question-count" type="number" min="1" max={configured.pricing.maximum_questions} step="1" required value={state.questions} onChange={e=>dispatch({type:'edit',name:'questions',value:Number(e.target.value)})}/></div>}<div className="field"><label htmlFor="appointment-date">Choose a date</label><input id="appointment-date" type="date" required min={range?.first_date||indiaDate()} max={maxDate} value={state.day} disabled={!state.policy||locked} onChange={e=>dispatch({type:'edit',name:'day',value:e.target.value})}/><p className="field-hint">Available times are checked when you choose a date.</p></div><p id="availability-message" role="status">{state.slotsStatus==='loading'?'Checking available times…':state.slotsStatus==='error'?'We cannot check the schedule right now. No times are being offered.':state.slotsStatus==='ready'?(state.slots.length?'Choose an available start time.':'There are no available times on this day. Please choose another date.'):'Choose a date to see available times.'}</p>{state.slotsStatus==='error'&&<button type="button" className="text-button" disabled={locked||state.loadingPolicy} onClick={flow.loadPolicy}>Retry available times</button>}<fieldset className="slot-grid"><legend>Available start times</legend>{state.slots.map(slot=><label className="slot-option" key={slot.starts_at}><input name="time" type="radio" value={slot.starts_at} checked={state.slot?.starts_at===slot.starts_at} onChange={()=>dispatch({type:'edit',name:'slot',value:slot})}/>{timeLabel(slot.starts_at,timezone)}</label>)}</fieldset><p className="field-hint">Choosing a time does not reserve it yet.</p><div className="section-action"><Go id="service">← Consultation</Go><button className="button" type="button" disabled={!state.slot||locked} onClick={()=>go('details')}>Your details →</button></div></div></div></section>
      <section className="details-section story-section wrap section-space" id="details" aria-labelledby="details-title"><div className="details-heading"><p className="eyebrow">03 / A PERSONAL BEGINNING</p><h2 id="details-title" tabIndex="-1">The details.<br/><em>Then the conversation.</em></h2><p>We’ll use these for your appointment details and any booking issues.</p></div><div className="details-grid"><div className="context-sheet"><div className="sheet-topline"><span>YOUR DETAILS</span><span>01 — 03</span></div>{[['full_name','Your name','text','name',100],['email','Email address','email','email',254]].map(([name,label,type,auto,max])=><div className="field" key={name}><label htmlFor={name}>{label} <span className="required-label">Required</span></label><input id={name} type={type} autoComplete={auto} required minLength={name==='full_name'?2:undefined} maxLength={max} value={state.details[name]} onChange={e=>dispatch({type:'details',name,value:e.target.value})}/>{name==='email'&&<p className="field-hint">Please check the spelling. {state.policy?.policy.booking_verification.email?'Verify this address below before continuing to payment.':'No email verification code is required.'}</p>}</div>)}<VerificationFields flow={flow} className="field" buttonClassName="text-button"/>
<div className="field"><label htmlFor="phone">Mobile number <span className="required-label">Required</span></label><div className="phone-group"><select aria-label="Country calling code" value={state.details.country} onChange={e=>dispatch({type:'details',name:'country',value:e.target.value})}>{[['91','India +91'],['44','UK +44'],['1','US / Canada +1'],['971','UAE +971'],['65','Singapore +65'],['61','Australia +61'],['other','Other country']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><input id="phone" type="tel" inputMode="tel" autoComplete="tel-national" required pattern={state.details.country==='other'?'\\+[1-9][0-9\\s\\(\\)\\-]{6,29}':'[0-9\\s\\(\\)\\-]{7,30}'} maxLength="30" value={state.details.phone} onChange={e=>dispatch({type:'details',name:'phone',value:e.target.value})}/></div><p className="field-hint">{state.details.country==='other'?'Include + and your country code.':'Enter the mobile number without the country code.'}</p></div>{(configured?.required_preparation||[]).filter(name=>name!=='notes').map(name=><div className="field" key={name}><label htmlFor={name}>{{birth_date:'Birth date',birth_time:'Birth time',birth_place:'Birth place'}[name]} <span className="required-label">Required</span></label><input id={name} type={name==='birth_date'?'date':name==='birth_time'?'time':'text'} required maxLength={200} value={state.details[name]} onChange={e=>dispatch({type:'details',name,value:e.target.value})}/></div>)}
<div className="field"><label htmlFor="notes">What would you like to discuss? <span className="optional">{configured?.required_preparation.includes('notes')?'Required':'Optional'}</span></label><textarea id="notes" required={configured?.required_preparation.includes('notes')} rows="4" maxLength="4000" value={state.details.notes} onChange={e=>dispatch({type:'details',name:'notes',value:e.target.value})}/><p className="field-hint">A sentence or two is enough. Leave private information for the consultation.</p></div><p className="privacy-note">Your details are sent when you continue to payment. Please review the <a href="/privacy" target="_blank" rel="noopener noreferrer">privacy policy</a>.</p><div className="section-action"><Go id="appointment">← Date & time</Go><button className="button" type="button" onClick={detailsNext}>Review your booking →</button></div></div><aside className="context-recap"><div className="recap-tab" aria-hidden="true">✦</div><p className="eyebrow">A THREAD TO FOLLOW</p><h3>Your conversation,<br/>taking shape.</h3><dl><div><dt>Consultation</dt><dd>{selectedName}</dd></div><div><dt>Date & time · {timezone}</dt><dd>{appointment}</dd></div></dl><span className="recap-line" aria-hidden="true"/><p>One step closer. Your choices stay with you as you move through the page.</p></aside></div></section>
    </fieldset>
    <section className="review-section story-section section-space" id="review" aria-labelledby="review-title"><div className="review-wrap"><div className="review-heading"><p className="eyebrow">04 / BRINGING IT TOGETHER</p><h2 id="review-title" tabIndex="-1">Your time.<br/><em>Considered and clear.</em></h2><p>Check your email, mobile number and appointment before you continue.</p></div>{!state.credential&&<div className="summary-sheet"><div className="summary-seam" aria-hidden="true"/>{[['Consultation',selectedName,service?`${service.duration_minutes} minutes · ${online?'Google Meet':'Practice-arranged meeting'}`:'Details unavailable','service'],['Date & time',appointment,timezone,'appointment'],['Your contact details',state.details.full_name||'Add your details',state.details.email+' · '+(state.details.country==='other'?'':'+'+state.details.country+' ')+state.details.phone,'details']].map(([label,value,sub,id],i)=><div className="summary-row" key={id}><span className="summary-number">0{i+1}</span><div><span className="summary-label">{label}</span><strong>{value}</strong><span className="summary-sub">{sub}</span></div><button className="edit-button" type="button" disabled={locked} onClick={()=>go(id)}>Edit</button></div>)}{state.details.notes&&<div className="summary-row"><span className="summary-number">↳</span><div><span className="summary-label">Your question</span><p>{state.details.notes}</p></div></div>}<div className="amount-plaque"><span>Total <small>Consultation fee</small></span><strong>{service?money(service.amount_paise):'—'}</strong></div><div className="review-bottom"><p>Continue to Razorpay’s secure payment window. Your appointment is confirmed only after your payment is checked.</p><label className="acknowledgement"><input type="checkbox" checked={state.ack} disabled={locked} onChange={e=>dispatch({type:'ack',value:e.target.checked})}/><span>I’ve checked my appointment, email and mobile number, and read the <a href="/booking-policy" target="_blank" rel="noopener noreferrer">booking policy</a> and <a href="/terms" target="_blank" rel="noopener noreferrer">terms</a>.</span></label><button className="button submit-button" type="submit" disabled={locked||!state.policy||!state.slot||!state.ack||(state.policy?.policy.booking_verification.email&&!state.verification)}>{state.busy?'Preparing your booking…':`Continue to payment${service?' · '+money(service.amount_paise):''} ↗`}</button></div></div>}{state.credential&&<Receipt {...flow}/>}</div></section></form>
    <section className="questions story-section wrap section-space" id="questions"><div className="section-intro"><p className="eyebrow">A LITTLE REASSURANCE</p><h2 tabIndex="-1">Before you<br/><em>begin.</em></h2><p>A few practical questions, with room for yours.</p><a className="text-button" href="/booking-help">Restore lost booking access ↗</a><Link className="text-button folded-link" to="/contact">Ask before booking <span>↗</span></Link></div><div className="question-list">{[
      ['When is my appointment confirmed?','Your appointment is confirmed after payment is checked and the booking is saved. Choosing a time alone does not reserve it.'],
      ['What if the payment screen closes?','Check the status of that booking first. A closed screen or expired timer does not tell us whether money moved. The page will guide you to the next safe step.'],
      ['How will we meet?',online?'Online appointments use Google Meet. Once your appointment is confirmed, this page shows the meeting link when it is ready. Meeting details are also prepared for email delivery.':'Please contact the practice for your meeting arrangements.'],
      ['Can I change my details?','Use Edit before starting payment. After checkout begins, check its status first. For a confirmed appointment, contact the practice for help with a correction.'],
    ].map(([question,answer],i)=><details key={question}><summary><span className="question-index">0{i+1}</span>{question}<span className="plus">+</span></summary><p>{answer}</p></details>)}</div></section>
    <footer className="site-footer wrap"><div><strong>Sarsa Jyotish Sansthan</strong><p>With Madhuri Gupta</p></div><div><Link to="/about">About Madhuri</Link><Link to="/services">Consultations</Link><Link to="/contact">Contact</Link></div><span>Your time. Your conversation.</span></footer>
  </div>;
}
