// Approved client-original HTML14 composition; live form and route actions replace preview controls.
import {useLayoutEffect,useRef,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import ContactForm from '../contact/ContactForm.jsx';
import {mountContactMotion} from '../contact/motion.mjs';
import '../contact/contact.css';

export default function ContactPage(){
 const root=useRef(null),navigate=useNavigate(),[topicRequest,setTopicRequest]=useState(null);
 useLayoutEffect(()=>{const previous=document.title;document.title='Contact | Sarsa Jyotish Sansthan';const cleanup=mountContactMotion(root.current);return()=>{cleanup();document.title=previous;};},[]);
 function handleClick(event){
  const book=event.target.closest('[data-book]');
  if(book){event.preventDefault();navigate('/booking');window.scrollTo(0,0);return;}
  const anchor=event.target.closest('a[href="#desk"]');
  if(anchor){event.preventDefault();setTopicRequest({topic:anchor.dataset.route==='existing'?'Existing booking':'Before booking',id:performance.now()});
   root.current.querySelector('#desk').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
   root.current.querySelector('#visitor-name')?.focus({preventScroll:true});}
 }
 return <div className="sarsa-contact" ref={root} onClick={handleClick}>
<a className="contact-skip" href="#desk">Skip to enquiry form</a>
<header className="site-header"><a className="brand" href="/">SARSA<span>JYOTISH SANSTHAN</span></a><nav aria-label="Main navigation"><a href="/about">About Madhuri</a><a href="/contact" aria-current="page">Contact</a><button className="button" data-book="true">Book a consultation <span aria-hidden="true">↗</span></button></nav></header>
<div className="contact-main" id="contact-main">
<section className="stage hero" id="scene-listening" aria-labelledby="hero-title"><div className="hero-heading"><p className="eyebrow">A CONVERSATION WITH THE PRACTICE</p><h1 id="hero-title">A question is<br/>a good <em>beginning.</em></h1></div><div className="listening-art" aria-hidden="true"><div className="room-light"></div><div className="portal-plane"></div><div className="oval-rim rim-left"></div><div className="oval-rim rim-right"></div><div className="correspondence-fragment fragment-question"><span>A LITTLE CLARITY</span><strong>There’s something<br/>I’d like to ask.</strong><i></i></div><div className="correspondence-fragment fragment-reply"><span>A PLACE TO BEGIN</span><strong>Let’s start<br/>with your question.</strong><b>↗</b></div><div className="ground-shadow"></div></div><div className="hero-bottom"><p>You don’t need to have everything figured out. Start with what you would like to know.</p><div className="actions"><a className="button ask-button" href="#desk">Ask a question <span aria-hidden="true">↗</span></a><button className="text-button" data-book="true">Ready to book?</button></div><p className="hero-signature">Sarsa Jyotish Sansthan <span>with Madhuri Gupta</span></p></div></section>
<section className="stage routes-stage" id="scene-routes" aria-labelledby="route-title"><div className="routes-heading"><p className="eyebrow">FIND YOUR WAY</p><h2 id="route-title">What brings you here?</h2></div><div className="route-junction"><div className="junction-line" aria-hidden="true"></div><span className="junction-marker" aria-hidden="true"></span>
<a className="route-lane" href="#desk" data-route="question"><span className="branch" aria-hidden="true"></span><span className="lane-number">01 / A QUESTION</span><strong>A little clarity.</strong><span className="lane-copy">Ask before choosing a consultation.</span><span className="lane-action">Write to the practice <i aria-hidden="true">↗</i></span></a>
<button className="route-lane booking-lane" data-route="booking" data-book="true"><span className="branch" aria-hidden="true"></span><span className="lane-number">02 / AN APPOINTMENT</span><strong>Ready to begin.</strong><span className="lane-copy">Choose a consultation and an available time.</span><span className="lane-action">Book a consultation <i aria-hidden="true">↗</i></span></button>
<a className="route-lane" href="#desk" data-route="existing"><span className="branch" aria-hidden="true"></span><span className="lane-number">03 / A LITTLE HELP</span><strong>Already booked?</strong><span className="lane-copy">Get help with an appointment or payment.</span><span className="lane-action">Ask about your booking <i aria-hidden="true">↗</i></span></a></div></section>
<section className="desk-section" id="desk" aria-labelledby="desk-title"><div className="section-intro"><p className="eyebrow">A NOTE TO THE PRACTICE</p><h2 id="desk-title">There’s room for<br/><em>what’s on your mind.</em></h2><p>A short message is enough to begin.</p></div><div className="stage desk-stage" id="scene-desk"><div className="desk-surface"><div className="desk-spine" aria-hidden="true"></div><div className="message-sheet"><div className="sheet-heading"><span>YOUR MESSAGE</span><span aria-hidden="true">✳</span></div><ContactForm topicRequest={topicRequest}/>
</div></div><aside className="desk-margin"><div className="reply-tab" aria-hidden="true">↗</div><p className="eyebrow">PERSONAL, FROM THE FIRST NOTE</p><h3>Start simply.<br/><em>We’ll take it<br/>from there.</em></h3><p>Ask about a consultation, share what you’d like to understand, or get help with a booking.</p><div className="margin-rule"></div><p className="margin-detail">Your name, email and a short message are enough. A phone number is optional.</p><p className="margin-detail">Sending an enquiry does not reserve an appointment.</p><button className="margin-book text-button" data-book="true">Prefer to choose a time? <span aria-hidden="true">↗</span></button></aside></div></section>
<section className="stage answers-stage" id="scene-answers" aria-labelledby="answers-title"><div className="answers-copy"><p className="eyebrow">BEFORE YOUR NEXT STEP</p><h2 id="answers-title">A little clarity.<br/><em>A clearer way forward.</em></h2><p>A few answers, so you can take the next step comfortably.</p><span className="quiet-mark" aria-hidden="true">?</span></div><div className="answer-book"><div className="answer-binding" aria-hidden="true"></div>
        <details className="answer-leaf"><summary><span className="leaf-index">01</span>Can I ask before choosing?<span className="leaf-corner" aria-hidden="true">↗</span></summary><div className="answer-body"><p>Yes. Use the enquiry form to explain what you would like to understand. You do not need to choose or pay for a consultation to ask a question.</p></div></details>
        <details className="answer-leaf"><summary><span className="leaf-index">02</span>How does online booking work?<span className="leaf-corner" aria-hidden="true">↗</span></summary><div className="answer-body"><p>Choose a consultation and an available time, enter your email and mobile number, then review and pay online. Your booking is confirmed after payment is verified. Appointment details follow separately.</p></div></details>
        <details className="answer-leaf"><summary><span className="leaf-index">03</span>Paid, but no confirmation?<span className="leaf-corner" aria-hidden="true">↗</span></summary><div className="answer-body"><p>Check the existing booking’s status before attempting another payment. If it needs attention, use the existing-booking help route and include your booking reference if you have one.</p></div></details>
        <details className="answer-leaf"><summary><span className="leaf-index">04</span>Should I send birth details here?<span className="leaf-corner" aria-hidden="true">↗</span></summary><div className="answer-body"><p>A general enquiry only needs enough context to understand your question. The booking journey will ask for the information needed for the selected consultation.</p></div></details>
      </div></section>
<section className="stage weave-stage" id="scene-weave" aria-labelledby="weave-title"><div className="weave-copy"><p className="eyebrow">WHEN YOU FEEL READY</p><h2 id="weave-title">Your next step.<br/><em>In your own time.</em></h2><p>Choose a consultation, find an available time, and make space for your questions with Madhuri Gupta.</p><button className="button light-button" data-book="true">Book a consultation <span aria-hidden="true">↗</span></button><a className="text-link" href="#desk">Or start with a question</a></div><div className="weave-art" aria-hidden="true"><div className="weave-light"></div><div className="weave-band band-one"><span>CHOOSE</span></div><div className="weave-band band-two"><span>PAY</span></div><div className="weave-band band-three"><span>CONFIRM</span></div><i className="weave-vertical vertical-one"></i><i className="weave-vertical vertical-two"></i><i className="weave-vertical vertical-three"></i><div className="weave-plaque"><span>A PERSONAL CONSULTATION</span><strong>A place for<br/>your questions.</strong><b>↗</b></div></div></section></div>
<footer className="site-footer"><div className="brand">SARSA<span>JYOTISH SANSTHAN</span></div><p>A thoughtful place to begin.<br/><small>Sarsa Jyotish Sansthan</small></p><a href="/booking">Book a consultation ↗</a><button type="button" className="text-button" data-motion="true" aria-pressed="true">Pause background movement</button></footer>

</div>;
}
