import {useRef,useState} from 'react';
import {PublicPage,copy,Action,NextStep} from '../site/PublicSections.jsx';
import {AnchorLink} from '../site/AnchorNavigation.jsx';
import ContactForm from '../contact/ContactForm.jsx';
import {useBookingProduct} from '../site/BookingProduct.jsx';
import map from '../site/map-location.json';
import '../contact/contact.css';
export default function ContactPage(){
 const [topicRequest,setTopicRequest]=useState(null),counter=useRef(0);
 const {enabled}=useBookingProduct();
 function request(topic){setTopicRequest({topic,id:++counter.current});}
 function focus(){return document.querySelector('#outcome')||document.querySelector('#code:not(:disabled)')||document.querySelector('#verification h3')||document.querySelector('#visitor-name:not(:disabled)')||document.querySelector('#desk-title');}
 return <PublicPage className="sarsa-contact">
 <section className="section"><div className="wrap contact-opening"><div><h1 tabIndex={-1}>{copy.contact.title}</h1><p className="hindi" lang="hi">{copy.contact.hindi}</p><p>{copy.contact.body}</p><div className="actions"><AnchorLink className="button" to="/contact#desk" focus={focus} onClick={()=>request('Before booking')}>Ask a question <span aria-hidden="true">↓</span></AnchorLink><Action to="/booking" bookingMode="hide">Book an appointment</Action></div></div><div className="correspondence"><article><span aria-hidden="true">✧</span><p>{copy.contact.card_one}</p></article><article><span aria-hidden="true">↗</span><p>{copy.contact.card_two}</p></article></div></div></section>
 <section className="section sage"><div className="wrap"><div className="section-heading"><h2>How can we help?</h2><Action to="/services" secondary>Explore services</Action></div><div className="three-column prose-columns"><article><h3>A question about a service</h3><AnchorLink className="button secondary" to="/contact#desk" focus={focus} onClick={()=>request('Before booking')}>Write your question <span aria-hidden="true">↓</span></AnchorLink></article><article><h3>{enabled?"Ready for an appointment?":"Choosing your guidance?"}</h3><Action to={enabled?"/booking":"/services"}>{enabled?"Book an appointment":"Explore our services"}</Action></article><article><h3>Already booked?</h3><AnchorLink className="button secondary" to="/contact#desk" focus={focus} onClick={()=>request('Existing booking')}>Ask about your booking <span aria-hidden="true">↓</span></AnchorLink></article></div></div></section>
 <section className="section" id="desk"><div className="wrap two-column"><div><h2 id="desk-title" tabIndex={-1}>{copy.contact.form_title}</h2><p>{copy.contact.form_explanation}</p><div className="enquiry-live"><ContactForm topicRequest={topicRequest}/></div></div><aside><h2>Start with your question.</h2><p>Ask about a service or get help with an existing appointment. Sending an enquiry does not reserve a time.</p><p>Keep birth details for your appointment. Do not send payment passwords or private access links.</p><a href="mailto:sarsajyotish@gmail.com">sarsajyotish@gmail.com</a></aside></div></section>
 <section className="section sage"><div className="wrap"><div className="section-heading"><div><h2>{copy.contact.map_title}</h2><address>{copy.brand.address}</address></div><a className="button secondary" href={map.owner_link} target="_blank" rel="noopener noreferrer">{copy.contact.directions_action} <span aria-hidden="true">↗</span></a></div><iframe className="map" title="Sarsa Jyotish Sansthan location: 8, Gailana Road, Agra" src={map.embed_url} loading="lazy" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/><p className="small">The map is provided by Google. The address and directions link remain available if the map cannot load.</p></div></section>
 <section className="section"><div className="wrap faq-wrap"><h2>{copy.contact.faq_title}</h2><div className="faq rail-faq">{copy.contact.faq.map(([question,answer],i)=><div className="rail-row" key={question}><span className="rail-badge" aria-hidden="true">0{i+1}</span><details name="sarsa-contact-faq"><summary>{question}<span className="faq-icon" aria-hidden="true"/></summary><p>{answer}</p></details></div>)}</div></div></section>
 <NextStep/>
 </PublicPage>;
}
