import {useParams,Navigate} from 'react-router-dom';
import {PublicPage,copy,Action,art,FAQ} from '../site/PublicSections.jsx';
export function Detail({service}){return <PublicPage className={'sarsa-services detail-'+service.id}>
 <section className="section"><div className="wrap two-column"><div><p className="service-name">{service.name}</p><h1 tabIndex={-1}>{service.title}</h1><p>{service.description}</p><div className="actions"><Action to={'/booking?service='+service.id} bookingMode="hide">Book an appointment</Action><Action to="/contact" secondary>Ask a question</Action></div></div><img className="detail-art" src={art(service.id)} width="640" height="320" alt=""/></div></section>
 <section className="section sage"><div className="wrap"><h2>What would you like to discuss?</h2><div className="three-column prose-columns">{service.topics.map(topic=><article key={topic}><h3>{topic}</h3></article>)}</div></div></section>
 {service.id==='kundli-prediction'&&<section className="section"><div className="wrap"><h2>Your chart, periods and planetary movements</h2><div className="three-column prose-columns"><article><h3>Your birth chart</h3><p>A kundli is the starting point for discussing your life questions through traditional Jyotish.</p></article><article><h3>Mahadasha and periods</h3><p>Ask how dasha periods are interpreted alongside your kundli and the questions you bring.</p></article><article><h3>Gochar and transits</h3><p>Discuss the traditional meaning of current grah movements alongside your birth chart.</p></article></div></div></section>}
 <section className="section"><div className="wrap two-column"><div><h2>{copy.detail_shared.how_title}</h2><p>{copy.detail_shared.how_body}</p></div><div><h2>{copy.detail_shared.preparation_title}</h2><p>{service.prepare}</p></div></div></section>
 <section className="section sage"><div className="wrap faq-wrap"><h2>Questions about {service.name}</h2><FAQ name={'sarsa-'+service.id+'-faq'} items={service.faq}/></div></section>
 <section className="section ending"><div className="wrap"><h2>Begin with your question.</h2><p>{copy.detail_shared.time_note}</p><div className="actions"><Action to={'/booking?service='+service.id} bookingMode="hide">Book an appointment</Action><Action to="/services" secondary>{copy.detail_shared.other_action}</Action></div></div></section>
 </PublicPage>;}
export default function ServiceDetail(){const {serviceId}=useParams(),service=copy.services.find(s=>s.id===serviceId);return service?<Detail service={service}/>:<Navigate to="/services" replace/>;}
